apiVersion: v1
kind: ConfigMap
metadata:
  name: amq-broker-springboot-starter-consumer-three
data:
  AMQ_BROKER_QUEUE: example::example
  AMQ_BROKER_0: amqp://amq-broker-ss-0.amq-broker-hdls-svc.amq-broker-dev.svc.cluster.local:5672
  AMQ_BROKER_1: amqp://amq-broker-ss-1.amq-broker-hdls-svc.amq-broker-dev.svc.cluster.local:5672
  AMQ_BROKER_URL: failover:(${AMQ_BROKER_0},${AMQ_BROKER_1})
  SPRING_APP_CONSUMER_NUMBER: THREE
